### ISSUE TITLE
Install Django and supporting libraries

### ISSUE THREAD

**Issue by Cushione** [Cushione/fantastic-news#2]
### Tasks
- [x] install 'django<4' gunicorn
- [x] install install dj_database_url psycopg2
- [x] install dj3-cloudinary-storage
