### ISSUE TITLE
Configure Admin panel

### ISSUE THREAD

**Issue by Cushione** [Cushione/fantastic-news#25]
As an editor, I want to be able to create, edit and delete news articles easily, so that I can efficiently control the content of the site.

### Acceptance Criteria
- The admin panel allows efficient content management

### Tasks
- [x] Add article and comment model
- [x] Add WYSIWYG Editor for the news article content
- [x] Adjust news article list and form
- [x] Adjust comment list and form
