### ISSUE TITLE
Add delete comment confirmation

### ISSUE THREAD

**Issue by Cushione** [Cushione/fantastic-news#38]
As a user, I want to see a confirmation dialog when I click the delete comment button so that I do not delete my comment by accident.

## Acceptance Criteria
- [x] When the user clicks on the delete comment button, a confirmation dialog requests a confirmation from the user
- [x] When the user confirms the deletion, the comment is deleted
- [x] When the user cancels the deletion, nothing happens
