### ISSUE TITLE
Add end-to-end tests

### ISSUE THREAD

**Issue by Cushione** [Cushione/fantastic-news#40]
- [x] Add Playwright to the project
- [x] Write tests for homepage
- [x] Write tests for article details
- [x] Write tests for login
- [x] Write tests for registration
- [x] Write tests for commenting
- [x] Write tests for liking
