### ISSUE TITLE
Add Cloudinary

### ISSUE THREAD

**Issue by Cushione** [Cushione/fantastic-news#5]
### Tasks
- [x] Create Cloudinary Account
- [x] Add Cloudinary URL to the project
- [x] Add libraries and add settings
