### ISSUE TITLE
Set up Heroku Deployment

### ISSUE THREAD

**Issue by Cushione** [Cushione/fantastic-news#6]
### Tasks
- [x] Create Heroku App
- [x] Link to Github Repository
- [x] Add Environment Variables (DISABLE_COLLECTSTATIC)
- [x] Add Proc File

**Comment by Cushione** [comment]
Heroku deployment successful. [Live Link](https://fantastic-news.herokuapp.com/)
